title: Adèle DEJOIE
description: M2 MVA student at ENS Paris-Saclay  Civil servent student at ENS Rennes
theme: jekyll-theme-minimal

email: adele.dejoie@ens-paris-saclay.fr
github_username: Myskdias
linkedin_username: Adèle Dejoie
